image: fedora:38

before_script:
  - dnf install -y git-core python3-pip python3-gobject gobject-introspection-devel gtk4-devel

test:
  stage: test
  script:
  - pip --cache-dir /tmp/pipcache install -e '.[dev]'
  - pip --cache-dir /tmp/pipcache install pre-commit
  - pre-commit run --all-files
  - pytest
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - /tmp/pipcache
