image: fedora:39

before_script:
  - >
    dnf install -y git-core python3-pip python3-gobject gobject-introspection-devel
    gtk4-devel gtksourceview5-devel libadwaita-devel gcr-devel gstreamer1-devel
    libshumate-devel libsoup3-devel vte291-gtk4-devel
    libportal-devel libportal-gtk4-devel webkitgtk6.0-devel
  - pip --cache-dir /tmp/pipcache install -e '.[dev]'

test:
  script:
  - pip --cache-dir /tmp/pipcache install pre-commit
  - pre-commit run --all-files
  - pytest --cov=pygobject_docs
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - /tmp/pipcache

pages:
  script:
  - ls /usr/share/gir-1.0
  - python3 -m pygobject_docs.generate $(cat libraries.txt)
  - sphinx-build -M html build/source build -c pygobject_docs 
  - mv build/html public
  artifacts:
    paths:
      - public
      - build/source
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
