image: python:3.11

before_script:
  - apt-get update -y
  - apt-get install -y libgirepository1.0-dev

test:
  stage: test
  script:
  - pip --cache-dir /tmp/pipcache install -e '.[dev]'
  - pip --cache-dir /tmp/pipcache install pre-commit
  - pre-commit run --all-files
  - pytest -m "not desktop"
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - /tmp/pipcache
