image: fedora:38

before_script:
  - dnf install -y git-core python3-pip python3-gobject gobject-introspection-devel gtk4-devel gtksourceview5-devel libadwaita-devel
  - pip --cache-dir /tmp/pipcache install -e '.[dev]'

test:
  stage: test
  script:
  - pip --cache-dir /tmp/pipcache install pre-commit
  - pre-commit run --all-files
  - pytest
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - /tmp/pipcache

pages:
  script:
  - ls /usr/share/gir-1.0
  - cat libraries.txt| xargs -L 1 python3 -m pygobject_docs.generate
  - sphinx-build -M html build/source build -c pygobject_docs 
  - mv build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH